In [2]:
from array import *

import numpy as np

n_rows = int(input("Enter number of rows: "))
n_cols = int(input("Enter number of columns: "))

arr = [[int(input("Enter value for {}. row and {}. column: ".format(r + 1, c + 1))) for c in range(n_cols)] for r in range(n_rows)]
ary = np.array(arr)
print(ary)

Enter number of rows: 4
Enter number of columns: 3
Enter value for 1. row and 1. column: 1
Enter value for 1. row and 2. column: 1
Enter value for 1. row and 3. column: 1
Enter value for 2. row and 1. column: 1
Enter value for 2. row and 2. column: 0
Enter value for 2. row and 3. column: -1
Enter value for 3. row and 1. column: 0
Enter value for 3. row and 2. column: 1
Enter value for 3. row and 3. column: -1
Enter value for 4. row and 1. column: 0
Enter value for 4. row and 2. column: 0
Enter value for 4. row and 3. column: -1
[[ 1  1  1]
 [ 1  0 -1]
 [ 0  1 -1]
 [ 0  0 -1]]


In [3]:
ary

array([[ 1,  1,  1],
       [ 1,  0, -1],
       [ 0,  1, -1],
       [ 0,  0, -1]])